[project]
name = "nerpda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "natasha>=1.6.0",
    "faker>=39.0.0",
    "bert-score>=0.3.13",
    "pymorphy3>=2.0.6",
    "transformers>=4.30.0",
]
